workflows:
  hello-world:
    instance_type: mac_mini_m1
    cache:
      cache_paths:
        - $HOME/.platformio/.cache
    triggering:
      events:
        - push
    name: Hello world workflow
    scripts:
      - name: Check Python
        script: python --version
      - name: Update PIP
        script: python -m pip install -U pip
      - name: Show current contect
        script: ls -al
      - name: Install dependencies
        script: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --skip-dependencies --global --platform symlink://.
      - name: Run example
        script: pio run -d examples/espidf-http-request
